name: Container1 Atrifact
on:
  
  workflow_dispatch:
    

jobs:
  ChromeJoinDepo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set ENV=branch-name
        id: extract-branch
        shell: bash
        run: echo "##[set-env name=ENV;]$(echo ${GITHUB_REF#refs/heads/})"
      - name: Set up JDK 14
        id: setup-jdk
        uses: actions/setup-java@v1
        with:
          java-version: 14
      - name: Cache
        id: maven-cache
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Maven Install
        if: steps.maven-cache.outputs.cache-hit != 'true'
        id: maven-install
        run: mvn clean install -DskipTests
      - name: Test in Linux
        id: run-test-complete
        shell: bash
        run: |
          mvn test -Dgroups=write -Dsurefire.suiteXmlFiles=testng.xml
      - uses: actions/upload-artifact@v3
        with:
          name: report1
          path: ./src/main/resources/report1.txt
          
  
  TriggerEmail:
    runs-on: ubuntu-latest
    needs: [ChromeJoinDepo]
    steps:
      - uses: actions/checkout@v2
      - name: Set ENV=branch-name
        id: extract-branch
        shell: bash
        run: echo "##$(echo ${GITHUB_REF#refs/heads/})"
      - name: Set up JDK 14
        id: setup-jdk
        uses: actions/setup-java@v1
        with:
          java-version: 14
      - name: Cache
        id: maven-cache
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Maven Install
        if: steps.maven-cache.outputs.cache-hit != 'true'
        id: maven-install
        run: mvn install -DskipTests
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v3
        with:
          name: report1
          path: ./src/main/resources/result1.txt
    
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: ./src/main/resources/result1.txt
      - uses: montudor/action-zip@v1
        with:
          args: unzip -qq ./src/main/resources/result1.zip -d ./src/main/resources/result1 
      - name: Test in Windows
        id: run-test-complete
        run: |
          mvn test -Dgroups=read -Dsurefire.suiteXmlFiles=testng.xml
      - uses: act10ns/slack@v1
        if: always()
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}  
